GradSchooler/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GradSchooler.Controllers
{
    public class CalendarController : Controller
    {
        public ActionResult Calendar()
        {
            ViewBag.User = User.Identity.Name;
            ViewBag.Date = Date();
            return View();
        }
        public ActionResult Deadline(){
            ViewBag.User = User.Identity.Name;
            ViewBag.Date = Date();
            return View();
        }

        [HttpPost]
        public ActionResult AddDeadline(){
            //db.submitDateRequest(deadline);
            string deadline = Request["deadline"];
            //Debug.WriteLine(" the deadline: " + deadline);
            return RedirectToAction(this.ControllerContext.RouteData.Values["controller"].ToString());
        }

        public string Date(){
            DateTime today = DateTime.Today;
            return today.ToString("yyyy-MM-dd");

        }
    }
}

GradSchooler/Views/Calendar/Calendar.cshtml
@using GradSchooler.Controllers;
@{
    string u = ViewBag.User;
    string date = ViewBag.Date;
    @Scripts.Render("~/bundles/custom") 
}

<!DOCTYPE html>
<html>
<head runat="server">
	<title>&nbsp;<h2>Program Deadlines</h2></title>
</head>
<body>
<iframe src="https://calendar.google.com/calendar/b/2/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=oo05b89hcnug8u7hsabrs2u5l0%40group.calendar.google.com&amp;color=%23875509&amp;ctz=America%2FLos_Angeles" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
<br/><h3><a href="@Url.Action("Deadline", "Calendar")"> Have a dead line to submit? Click here!</a></h3>	    
</body>

GradSchooler/Views/Calendar/Deadline.cshtml
@using GradSchooler.Controllers;
@{
    string u = ViewBag.User;
    string date = ViewBag.Date;
    @Scripts.Render("~/bundles/custom") 
}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
    </head>
    <body>
        @using (Html.BeginForm("AddDeadline", "Calendar", FormMethod.Post)){
        <div>
            <div class="container">
                <div class="card mx-auto mt-5 w-25">
                    <div class="card-header">Report a deadline!</div>
                    <div class="card-body">
                        <div class="form-group">
                            <form>
                                <div class="form-group">
                                    <label for="progname">Program Name</label>
                                    <input type="text" name="progname" value="@Request.Form[" progname"]" placeholder="" required>
                                </div><div class="form-group">
                                    <label for="uniname">University Name</label>
                                    <input type="text" name="uniname" value="@Request.Form[" uniname"]" placeholder="" required>
                                </div><div class="form-group">
                                    <label for="deadline">Deadline</label>
                                    <input type="date" name="deadline" max='2025-01-01' min='@date' class="form-control">
                                </div><div class="form-group">
                                <div class="form-group">
                                    <label for="lastname">Additional Notes</label><br/>
                                    <input type="text" name="progname" value="@Request.Form["progname"]" placeholder="" required>
                                </div>
                                    <input type="submit" class="btn btn-primary">
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        }
    </body>
</html>