GradSchooler/Models/University.cs
using System;
namespace GradSchooler.Models
{
    public class University
    {
        public string name { get; set; }
        public string fundingtype { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string environment { get; set; }
        public string url { get; set; }
        public string address { get; set; }

    }
}

GradSchooler/Controllers/CreateAccountController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GradSchooler.DBUtilities;
using GradSchooler.Models;

namespace GradSchooler.Controllers
{
    public class CreateAccountController : Controller
    {
        /// <summary>
        /// Creates the account form.
        /// </summary>
        /// <returns>The account form.</returns>
        public ActionResult CreateAccountForm()
        {
            ViewBag.Title = "Enter Account Info"; 
            return View();
        }//end CreateAccountForm
        
        /// <summary>
        /// Creates the account page.
        /// </summary>
        /// <returns>The account page.</returns>
        public ActionResult CreateAccountPage()
        {
            ViewBag.Title = "Account Creation Page";
            //create Account model
            Account a = new Account();
            Profile p = new Profile();
            //get user response
            Console.Write(Request.HttpMethod);
            if (Request.HttpMethod == "POST")
            {
                a.email = Request.Form["email"];
                a.password = Request.Form["password"];
                a.firstName = Request.Form["firstName"];
                a.lastName = Request.Form["lastName"];
                a.birthday = Request.Form["birthday"];

                //empty profile created with account creation
                p.pEmail = Request.Form["email"];
                p.favUnis = null;
                p.deadlines = null;

                DBUtilities.DBUtilities db = DBUtilities.DBUtilities.Instance;

                //pass Account model object to the database to create the account
                db.createAccount(a);
                return View("/Views/Login/Login.cshtml");
            }
            return View();
        }//end CreateAccountPage()

    }//end CreateAccountController
}//namespace

GradSchooler/Controllers/UniversityController.cs
using GradSchooler.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GradSchooler.Controllers
{
    public class UniversityController : Controller
    {
        /// <summary>
        /// Default method that displays all universities when university page is accessed
        /// </summary>
        /// <returns>The university.</returns>
        [HttpGet]
        public ActionResult University(int page = 0)
        {
            const int pageSize = 15; //number of elements per page

            ViewBag.Message = "University Page";

            DBUtilities.DBUtilities db = DBUtilities.DBUtilities.Instance;
            List <University> univs = new List<University>();

            univs = db.getUniversities("", "");
            var count = univs.Count;
            var data = univs.Skip(page * pageSize).Take(pageSize).ToList();
            ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
            ViewBag.Page = page;

            ViewData["unis"] = data;

            return View(data); //automatically returns the University View
        }//end of get method

        /// <summary>
        /// Called when a user is searching for a specific university
        /// by entering a search keyword
        /// </summary>
        [HttpPost]
        public ActionResult University(String keyword){
            string searchType = "";
            if(!String.IsNullOrEmpty(Request["name"])){
                keyword = Request["name"];
                searchType = "name";
            }
            else if (!String.IsNullOrEmpty(Request["city"]))
            {
                keyword = Request["city"];
                searchType = "city";
            }
            else if (!String.IsNullOrEmpty(Request["state"]))
            {
                keyword = Request["state"];
                searchType = "state";
            }
            else if (!String.IsNullOrEmpty(Request["url"]))
            {
                keyword = Request["url"];
                searchType = "uniUrl";
            }

            ViewBag.Message = "University Page";

            DBUtilities.DBUtilities db = DBUtilities.DBUtilities.Instance;
            List<University> univs = new List<University>();

            univs = db.getUniversities(keyword, searchType);
            ViewData["unis"] = univs;

            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FavoriteUniversity()
        {
            if (ModelState.IsValid)
            {
                DBUtilities.DBUtilities db = DBUtilities.DBUtilities.Instance;

                String curEmail = User.Identity.Name;//get the email of the person logged in

                //get post data from request object
                List<String> favUnisData = new List<String>();

                foreach(var key in Request.Form.AllKeys)
                {
                    if (key.StartsWith("favUnis"))
                    {
                        String s = Convert.ToString(Request.Form[key]);
                        String[] values = s.Split(',');
                        foreach(var item in values)
                        {
                            db.addFavUniversity(curEmail, item); //add favUni to database
                        }//end foreach
                    }//end if
                }//end foreach


                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("","This action cannot be performed");
            }

            return View();
        }//end of post method

        /// <summary>
        /// Returns the view of the SingleUniversity page in order
        /// for a user to view the data of one university
        /// </summary>
        /// <param name="u"></param>
        /// <returns></returns>
        public ActionResult SingleUniversity(University u)
        {
            ViewData["uni"] = u;
            return View();
        }

        /// <summary>
        /// Returns the view of the SingleUniversity page with a form 
        /// in order for a user to change the data of one university
        /// </summary>
        /// <param name="u"></param>
        /// <param name="s"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SingleUniversity(University u, string s){

            s = "NULL";
            String curEmail = User.Identity.Name; //the user that is logged in

            DBUtilities.DBUtilities db = DBUtilities.DBUtilities.Instance;
            db.addURequest(u, curEmail, s);

            return RedirectToAction("University", "University");
        }


    }//end of class
   
}//end of namespace

GradSchooler/Views/University/SingleUniversity.cshtml
@using GradSchooler.Models
@model GradSchooler.Models.University
@{ 
    ViewBag.Title = "University";
    University item = (University)ViewData["uni"];

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>University Information</title>
   
</head>
<body>
    <div class="container">
    <p class="lead"><h3>University Information</h3></p>
    </div>

    <!-- diaplay university information -->
    @using (Html.BeginForm("SingleUniversity", "University", FormMethod.Post))
    {
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Website</th>
                <th>City</th>
                <th>State</th>
                <th>Environment</th>
            </tr>
            <tr>
                 <td>@item.name</td>
                 <td><a href="http://@item.url">@item.url</a></td>
                 <td>@item.city</td>
                 <td>@item.state</td>
                 <td>@item.environment</td>
            </tr>
        </table>
        <br/>
    }
    <p class="lead"><h4>&nbsp;&nbsp; <em>Want to contribute to GradSchooler's database info?</em> 
        <small class="text-muted">Fill out the form below.</small></h4><p/>

    @if (Request.IsAuthenticated) {
        <!-- Form to submit new university info -->
        using (Html.BeginForm("SingleUniversity", "University", item, FormMethod.Post))
        {   
            
            <div class="container">
                <label for="fundingtype">Funding Type</label><br>
                @Html.TextBoxFor(u => u.fundingtype, new { @class = "form-control", tabindex = 1 })        
                <br>

                <label for="city">City</label><br>
                @Html.TextBoxFor(u => u.city, new { @class = "form-control", tabindex = 2 })        
                <br>
            
                <label for="state">State</label><br>
                @Html.TextBoxFor(u => u.state, new { @class = "form-control", tabindex = 3 })        
                <br>

                <label for="environment">Environment</label><br>
                @Html.TextBoxFor(u => u.environment, new { @class = "form-control", tabindex = 4 })        
            

                <br>
                <input type="submit" class="btn btn-primary" value="Submit">
            </div>
        }
    }else{
        <div class="card text-center border-dark mb-3">
            <div class="card-header">
                <h4>Sign in to contibute to GradSchooler's information!</h4>
            </div>
            <div class="card-body">
                <a href="@Url.Action("Login", "Login")" class="btn btn-primary">Sign In</a>
                <a href="@Url.Action("CreateAccountPage", "CreateAccount")" class="btn btn-primary">Create an Account</a> 
            </div>
        </div>
    }

</body>
</html>

GradSchooler/Views/University/University.cshtml
@{
    ViewBag.Title = "University";
    var unis = ViewBag.unis;
    string search = "";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GradSchooler</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/custom")
</head>
<body>

            <div class="table-responsive">          
                <table class="table">
                    <thead>
                        <tr>
                            @if(Request.IsAuthenticated){<th></th>}
                            <th>University</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Website</th>        
                        </tr>
                        <tr>
                            @if(Request.IsAuthenticated){<th></th>}
                            <th>
                                @using (Html.BeginForm("University", "University", search, FormMethod.Post))
                                {
                                    <input type="text" class="form-control" name="name" placeholder="University" value="">
                                }
                            </th>
                            <th>
                                @using (Html.BeginForm("University", "University", search, FormMethod.Post))
                                {
                                    <input type="text" class="form-control" name="city" placeholder="City" value="">
                                }
                            </th>
                            <th>
                                @using (Html.BeginForm("University", "University", search, FormMethod.Post))
                                {
                                    <input type="text" class="form-control" name="state" placeholder="State" value="">
                                }
                            </th>
                            <th>
                                @using (Html.BeginForm("University", "University", search, FormMethod.Post))
                                {
                                    <input type="text" class="form-control" name="url" placeholder="Url" value="">
                                }
                            </th>
                        </tr>
                      </thead>
                </table>

                @using(Html.BeginForm("FavoriteUniversity", "University", FormMethod.Post, new { name = "FavForm", id = "FavForm"})){
                <table class="table">
                        @foreach (var item in unis)
                        {
                            String url = (item.url).ToLower();
                            <tbody id="unis">
                                <tr>
                                    @if(Request.IsAuthenticated){<td width="40px"><input type="checkbox" name="favUnis" value="@item.name" /></td>}
                                    <td width="25%"><a href = "@Url.Action("SingleUniversity", "University", item)">@item.name</a></td>
                                    <td width="25%">@item.city</td>
                                    <td width="25%">@item.state</td>
                                    <td width="25%"><a href="http://@url">@url</a></td>
                                </tr>
                            </tbody>
                        }     
                </table>
                if(Request.IsAuthenticated){<input type="submit" class="btn btn-primary" name="Favorite" value="Favorite">}
             }
             </div>
             <br/>
       
             

@if (ViewBag.Page > 0)
{
    <a href="@Url.Action("University", "University", ViewBag.Page + 1)" 
       class="btn btn-default">
        &laquo; Prev
    </a>
}
@if (ViewBag.Page < ViewBag.MaxPage)
{
    <a href="@Url.Action("University", new { page = ViewBag.Page + 1 })" 
       class="btn btn-default">
        Next &raquo;
    </a>
}  
</body>
</html>